---
- hosts: ub
  become: true
  tasks:
  - name: Copying .war file to Tomcat server
    copy:
      src: war-file/target/addressbook-2.0.war
      dest: /usr/local/tomcat/webapps/addressbook-2.0.war
